sudo: required
services:
  - docker

before_install:
  - docker build -t ickyblindman/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ickyblindman/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "aws-test"
  env: "AwsTest-env"
  bucket_name: "elasticbeanstalk-us-east-1-022924706999"
  bucket_path: "aws-test"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
